package poseidon_test

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"os"
	"strconv"
	"testing"

	"github.com/bronlabs/bron-crypto/pkg/base/curves/pasta"
	minaposeidon "github.com/node101-io/mina-signer-go/poseidon"
	"github.com/stretchr/testify/require"
)

var preGeneratedHashes = make(map[string]string)

func init() {

	// Note that these hashes are not o1js's test vectors.
	// These are generated by this repo's maintainers.
	hashes := []string{
		"23608266625797871040826122723800669223871240056197278634405806036556889433248",
		"18146286282275317050852786039646244402878559860774406775641563417373390261699",
		"25214055403451732710721922171450367779839014469616988132694858281638215621996",
		"26431347576821735725721898577434109426312629679243614950359163921429170013399",
		"24533484825816384350875706453714685830410901441209786907190693135525931689795",
		"9046738680902586510432297093870232673359511002471493971225609043996631039530",
		"491382324087868585616829488574348533752788271803529241884472760368326342994",
		"27443117374193591451033882876415841583362734859190455361121968279138661852968",
		"10961914516818006663852165456878415680533871924230200845565073682381474582772",
		"14137951692495747281604853008431147305293375022877360908576136891591983235983",
	}

	for i, hash := range hashes {
		preGeneratedHashes["message"+strconv.Itoa(i+1)] = hash
	}

}

type testVector struct {
	Input  []string `json:"input"`
	Output string   `json:"output"`
}

const prefix string = "pulsar"
const o1jsTestVectorFile string = "test_vectors.json"

func reverseBytes(b []byte) []byte {
	out := make([]byte, len(b))
	for i := range b {
		out[i] = b[len(b)-1-i]
	}
	return out
}

func readTestVectorsFile(path string) ([]testVector, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var vectors []testVector

	dec := json.NewDecoder(f)
	if err := dec.Decode(&vectors); err != nil {
		return nil, err
	}

	return vectors, nil
}

func TestPoseidonHashVectors(t *testing.T) {

	poseidon := minaposeidon.NewPoseidon()

	hasher, err := poseidon.GetHasher()
	require.NoError(t, err)
	require.NotNil(t, hasher)

	vector, err := readTestVectorsFile(o1jsTestVectorFile)
	require.NoError(t, err)
	require.NotNil(t, vector)

	for _, vect := range vector {

		hasher.Reset()

		inputs := make([]*pasta.PallasBaseFieldElement, 0, len(vect.Input))

		for _, input := range vect.Input {

			msg, err := hex.DecodeString(input)
			require.NoError(t, err)
			require.NotNil(t, msg)

			hashField, err := pasta.NewPallasBaseField().FromBytes(reverseBytes(msg))
			require.NoError(t, err)
			require.NotNil(t, hashField)

			inputs = append(inputs, hashField)
		}

		for len(inputs)%hasher.Rate() != 0 {
			inputs = append(inputs, pasta.NewPallasBaseField().Zero())
		}

		err = hasher.Update(inputs...)
		require.NoError(t, err)

		hash := hasher.Digest()
		encoded := hex.EncodeToString(reverseBytes(hash.Bytes()))

		require.Equal(t, vect.Output, encoded)
	}

}

func TestPoseidonHashwithPrefix(t *testing.T) {

	for msg, pregenHash := range preGeneratedHashes {

		poseidon := minaposeidon.NewPoseidon()

		hash, err := poseidon.HashWithPrefix(prefix, []byte(msg))
		require.NoError(t, err)
		require.NotNil(t, hash)

		hashField, err := pasta.NewPallasBaseField().FromBytes(hash)
		require.NoError(t, err)
		require.NotNil(t, hashField)

		require.Equal(t, pregenHash, hashField.String())
	}

}

func TestHashDivisibleByBronRate(t *testing.T) {

	b := make([]byte, 64)

	_, err := rand.Read(b)
	require.NoError(t, err)

	poseidon := minaposeidon.NewPoseidon()

	hash, err := poseidon.Hash(b)
	require.NoError(t, err)
	require.NotNil(t, hash)

}
func TestHashNotDivisibleByBronRate(t *testing.T) {

	b := make([]byte, 65)

	_, err := rand.Read(b)
	require.NoError(t, err)

	poseidon := minaposeidon.NewPoseidon()

	hash, err := poseidon.Hash(b)
	require.NoError(t, err)
	require.NotNil(t, hash)

}
