package merklelist

import (
	"testing"

	"github.com/bronlabs/bron-crypto/pkg/base/curves/pasta"
	"github.com/stretchr/testify/require"
)

const prefix string = "pulsar"

// Note that this is not o1js's test vector.
// This is generated by this repo's maintainers.
const validRoot string = "27371407983650058557167762723891068921859450186598884274366871258199362618277"

func TestMerkleList(t *testing.T) {
	merkleList, err := NewMerkleList(prefix)
	require.NoError(t, err)

	field := pasta.NewPallasBaseField()

	for i := 1; i <= 10; i++ {
		err := merkleList.Append(field.FromUint64(uint64(i)).Bytes())
		require.NoError(t, err)
	}

	rootField, err := field.FromBytes(merkleList.Root())
	require.NoError(t, err)
	require.NotNil(t, rootField)

	require.Equal(t, rootField.String(), validRoot)
}
